# -*- coding: utf-8 -*-
"""Market_basket_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mL-K1OZRUwUH7spNT2NSTvEalAEpQtVJ
"""

!pip install apyori

# Importing basic libraries
import numpy as np #arrays
import pandas as pd #tabular
from apyori import apriori #association between two data items

# Loading Dataset
df = pd.read_csv("/content/store_data.csv", header=None)

# the first 10 rows of dataset
df.head(10)

# Shape of the dataset
df.shape

# create list of transactions (list)
records = []
for i in range(0, 7501):
    records.append([str(df.values[i,j]) for j in range(0, 20)])

rules = apriori(records, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=2)
results = list(rules)

for item in results:
    pair = item[0]
    items = [i for i in pair]
    if items[0] == 'nan' or items[1] == 'nan':
        continue
    print("You should keep", items[1], "next to", items[0])